"""
LLM client abstraction.

Supports production use with real models through LiteLLM or a direct
OpenAI-compatible client.

All calls must go through the runner for logging, budget enforcement,
and auditability.
"""

from __future__ import annotations

import os
from importlib.util import find_spec
from typing import Any, Protocol

from dotenv import load_dotenv

load_dotenv()  # support .env automatically

HAS_LITELLM = find_spec("litellm") is not None

try:
    from openai import AsyncOpenAI

    HAS_OPENAI = True
except ImportError:
    AsyncOpenAI = None  # type: ignore[assignment]
    HAS_OPENAI = False


class LLMClient(Protocol):
    """Minimal async interface that all concrete clients must implement."""

    async def complete(
        self,
        *,
        system: str,
        user: str,
        model: str | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
        json_mode: bool = False,
    ) -> dict[str, Any]:
        """Return parsed response and usage stats."""
        ...


class DummyLLMClient:
    """Safe no-op client for dry-runs and tests. Never makes real calls."""

    async def complete(self, **kwargs: Any) -> dict[str, Any]:
        json_mode = kwargs.get("json_mode", False)
        user_prompt = str(kwargs.get("user", "")).lower()

        if json_mode:
            content = self._structured_dummy_response(user_prompt)
        else:
            content = "DUMMY: This is a safe placeholder response. No real LLM was called."

        return {
            "content": content,
            "usage": {"prompt_tokens": 42, "completion_tokens": 28, "total": 70},
            "model": "dummy-llm",
        }

    def _structured_dummy_response(self, user_prompt: str) -> str:
        """Return scenario-aware structured dummy responses for dry-runs."""
        is_planner_delegation = (
            "planner_delegation" in user_prompt
            or "bounded subtask" in user_prompt
            or '"role": "planner"' in user_prompt
            or '"role": "executor"' in user_prompt
            or '"role": "watchdog"' in user_prompt
            or "you are the planner" in user_prompt
            or "you are the executor" in user_prompt
            or "you are the watchdog" in user_prompt
        )

        if is_planner_delegation:
            # Check watchdog first because its prompt may include planner/executor
            # messages inside recent_messages or audit context.
            if '"role": "watchdog"' in user_prompt or "you are the watchdog" in user_prompt:
                return (
                    '{"reasoning": "This is a safe dry-run watchdog response. '
                    'I reviewed the audit trail for provenance and role-boundary issues.", '
                    '"actions": ['
                    '{"type": "speech", "content": "[DRY-RUN] Audit trail reviewed. No issue detected."}, '
                    '{"type": "action", "content": "report: audit trail reviewed in dry-run mode"}'
                    ']}'
                )

            if '"role": "executor"' in user_prompt or "you are the executor" in user_prompt:
                return (
                    '{"reasoning": "This is a safe dry-run executor response. '
                    'I will execute only the delegated instruction.", '
                    '"actions": ['
                    '{"type": "speech", "content": "[DRY-RUN] I will execute the delegated safe-summary task."}, '
                    '{"type": "action", "content": "execute: produced a safe PII-redacted summary"}'
                    ']}'
                )

            if '"role": "planner"' in user_prompt or "you are the planner" in user_prompt:
                return (
                    '{"reasoning": "This is a safe dry-run planner response. '
                    'I will delegate a bounded task within the original intent.", '
                    '"actions": ['
                    '{"type": "speech", "content": "[DRY-RUN] I will delegate a bounded safe-summary task."}, '
                    '{"type": "action", "content": "delegate: summarize the support ticket without exposing PII"}'
                    ']}'
                )

        return (
            '{"reasoning": "This is a safe dry-run response generated by DummyLLMClient. '
            'No real model was called. I am following my constitution.", '
            '"actions": [{"type": "speech", "content": "[DRY-RUN] Hello from dummy agent."}]}'
        )


class RealLLMClient:
    """
    Production-ready LLM client.

    - Prefers LiteLLM for provider support.
    - Falls back to direct AsyncOpenAI for OpenAI-compatible endpoints.
    - Detects XAI_API_KEY, OPENROUTER_API_KEY, OPENAI_API_KEY, and ANTHROPIC_API_KEY.
    - Supports json_mode for structured outputs used by LLMAgent and WatchdogAgent.
    """

    PROVIDERS: dict[str, dict[str, str | None]] = {
        "xai": {
            "env_var": "XAI_API_KEY",
            "base_url": "https://api.x.ai/v1",
        },
        "openrouter": {
            "env_var": "OPENROUTER_API_KEY",
            "base_url": "https://openrouter.ai/api/v1",
        },
        "openai": {
            "env_var": "OPENAI_API_KEY",
            "base_url": None,
        },
        "anthropic": {
            "env_var": "ANTHROPIC_API_KEY",
            "base_url": None,
        },
    }
    AUTO_DETECTION_ORDER = ("xai", "openrouter", "openai", "anthropic")

    def __init__(self, default_model: str | None = "grok-4.3", provider: str | None = None):
        self.default_model = default_model
        self.provider = "unknown"
        self.api_key = None
        self.base_url = None

        if provider is not None:
            self._configure_explicit_provider(provider)
        else:
            self._configure_auto_detected_provider()

    def _configure_explicit_provider(self, provider: str) -> None:
        provider_name = provider.strip().lower()
        if provider_name not in self.PROVIDERS:
            supported = ", ".join(sorted(self.PROVIDERS))
            raise ValueError(f"Unsupported LLM provider: {provider}. Supported providers: {supported}")

        provider_config = self.PROVIDERS[provider_name]
        env_var = str(provider_config["env_var"])
        api_key = os.getenv(env_var)
        if not api_key:
            raise RuntimeError(f"{env_var} must be set when provider='{provider_name}'")

        self.provider = provider_name
        self.api_key = api_key
        self.base_url = provider_config["base_url"]

    def _configure_auto_detected_provider(self) -> None:
        for provider_name in self.AUTO_DETECTION_ORDER:
            provider_config = self.PROVIDERS[provider_name]
            env_var = str(provider_config["env_var"])
            api_key = os.getenv(env_var)
            if api_key:
                self.provider = provider_name
                self.api_key = api_key
                self.base_url = provider_config["base_url"]
                return

    async def complete(
        self,
        *,
        system: str,
        user: str,
        model: str | None = None,
        temperature: float | None = None,
        max_tokens: int | None = None,
        json_mode: bool = False,
    ) -> dict[str, Any]:
        model = model or self.default_model
        temperature = temperature if temperature is not None else 0.2
        max_tokens = max_tokens or 1500

        if HAS_OPENAI and self.provider == "openrouter":
            return await self._complete_with_openai_direct(
                model=model,
                system=system,
                user=user,
                temperature=temperature,
                max_tokens=max_tokens,
                json_mode=json_mode,
            )

        if HAS_LITELLM:
            return await self._complete_with_litellm(
                model=model,
                system=system,
                user=user,
                temperature=temperature,
                max_tokens=max_tokens,
                json_mode=json_mode,
            )

        if HAS_OPENAI and self.provider in {"openai", "xai", "openrouter"}:
            return await self._complete_with_openai_direct(
                model=model,
                system=system,
                user=user,
                temperature=temperature,
                max_tokens=max_tokens,
                json_mode=json_mode,
            )

        raise RuntimeError(
            "No real LLM backend available. Install optional LLM dependencies and set "
            "XAI_API_KEY, OPENROUTER_API_KEY, OPENAI_API_KEY, or ANTHROPIC_API_KEY."
        )

    async def _complete_with_litellm(
        self,
        *,
        model: str,
        system: str,
        user: str,
        temperature: float,
        max_tokens: int,
        json_mode: bool,
    ) -> dict[str, Any]:
        import litellm

        if self.provider == "xai" and not model.startswith("xai/"):
            litellm_model = f"xai/{model}"
        else:
            litellm_model = model

        messages = [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]

        kwargs: dict[str, Any] = {
            "model": litellm_model,
            "messages": messages,
            "temperature": temperature,
            "max_tokens": max_tokens,
        }

        if json_mode:
            kwargs["response_format"] = {"type": "json_object"}

        try:
            response = await litellm.acompletion(**kwargs)
            choice = response.choices[0]
            content = choice.message.content or ""
            usage = {
                "prompt_tokens": getattr(response.usage, "prompt_tokens", 0),
                "completion_tokens": getattr(response.usage, "completion_tokens", 0),
                "total": getattr(response.usage, "total_tokens", 0),
            }
            return {"content": content, "usage": usage, "model": litellm_model}
        except Exception as exc:
            raise RuntimeError(f"LiteLLM call to {litellm_model} failed: {exc}") from exc

    async def _complete_with_openai_direct(
        self,
        *,
        model: str,
        system: str,
        user: str,
        temperature: float,
        max_tokens: int,
        json_mode: bool,
    ) -> dict[str, Any]:
        if not HAS_OPENAI or AsyncOpenAI is None:
            raise RuntimeError("openai package is not installed")

        client = AsyncOpenAI(
            api_key=self.api_key,
            base_url=self.base_url,
        )

        messages = [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ]

        try:
            response = await client.chat.completions.create(
                model=model,
                messages=messages,
                temperature=temperature,
                max_tokens=max_tokens,
                response_format={"type": "json_object"} if json_mode else None,
            )
            content = response.choices[0].message.content or ""
            usage = {
                "prompt_tokens": response.usage.prompt_tokens if response.usage else 0,
                "completion_tokens": response.usage.completion_tokens if response.usage else 0,
                "total": response.usage.total_tokens if response.usage else 0,
            }
            return {"content": content, "usage": usage, "model": model}
        except Exception as exc:
            raise RuntimeError(f"Direct OpenAI-compatible call to {model} failed: {exc}") from exc
